"""Exact certificate for conventional-level Stringer coverage at ``n=4``.

For ``alpha`` equal to 0.01, 0.05, or 0.10, this module proves that the
binomial Stringer bound pointwise dominates the one-sided Gaffke bounded-mean
upper limit.  It evaluates the polynomial structure generated by
:mod:`derive_n4_bernstein_structure` with exact rational interval arithmetic.
Clopper--Pearson factor brackets have dyadic endpoints whose binomial-CDF
signs are checked using integers.  Floating point is used only for readable
summaries, never for a sign decision.
"""

from __future__ import annotations

import argparse
import ast
import hashlib
import json
import math
from dataclasses import dataclass
from fractions import Fraction
from pathlib import Path

from stringer import exact_binomial_factor_brackets


ALPHAS = ("0.01", "0.05", "0.10")
FACTOR_BITS = 120
HERE = Path(__file__).resolve().parent
CERTIFICATE_DIR = HERE.parent / "certificates"
STRUCTURE_PATH = CERTIFICATE_DIR / "n4-gaffke-bernstein-structure.json"


@dataclass(frozen=True)
class Interval:
    """Closed interval with exact rational endpoints."""

    lower: Fraction
    upper: Fraction

    def __init__(self, lower=0, upper=None):
        if isinstance(lower, Interval):
            object.__setattr__(self, "lower", lower.lower)
            object.__setattr__(self, "upper", lower.upper)
            return
        lo = Fraction(lower)
        hi = lo if upper is None else Fraction(upper)
        if lo > hi:
            raise ValueError("interval endpoints are reversed")
        object.__setattr__(self, "lower", lo)
        object.__setattr__(self, "upper", hi)

    def __add__(self, other):
        if isinstance(other, Polynomial3):
            return NotImplemented
        other = Interval(other)
        return Interval(self.lower + other.lower,
                        self.upper + other.upper)

    __radd__ = __add__

    def __neg__(self):
        return Interval(-self.upper, -self.lower)

    def __sub__(self, other):
        if isinstance(other, Polynomial3):
            return NotImplemented
        return self + (-Interval(other))

    def __rsub__(self, other):
        return Interval(other) - self

    def __mul__(self, other):
        if isinstance(other, Polynomial3):
            return NotImplemented
        other = Interval(other)
        products = (
            self.lower * other.lower,
            self.lower * other.upper,
            self.upper * other.lower,
            self.upper * other.upper,
        )
        return Interval(min(products), max(products))

    __rmul__ = __mul__

    def reciprocal(self):
        if self.lower <= 0 <= self.upper:
            raise ZeroDivisionError("interval contains zero")
        return Interval(1 / self.upper, 1 / self.lower)

    def __truediv__(self, other):
        return self * Interval(other).reciprocal()

    def __rtruediv__(self, other):
        return Interval(other) / self

    def __pow__(self, exponent):
        result = Interval(1)
        base = self
        while exponent:
            if exponent & 1:
                result = result * base
            base = base * base
            exponent //= 2
        return result


class Polynomial3:
    """Sparse polynomial in standard-tetrahedron coordinates ``U,V,W``."""

    def __init__(self, coefficients=None):
        self.coefficients = {}
        for index, value in (coefficients or {}).items():
            value = Interval(value)
            if value.lower != 0 or value.upper != 0:
                self.coefficients[index] = value

    @classmethod
    def constant(cls, value):
        return cls({(0, 0, 0): Interval(value)})

    def __add__(self, other):
        if not isinstance(other, Polynomial3):
            other = Polynomial3.constant(other)
        coefficients = dict(self.coefficients)
        for index, value in other.coefficients.items():
            coefficients[index] = coefficients.get(
                index, Interval(0)) + value
        return Polynomial3(coefficients)

    __radd__ = __add__

    def __neg__(self):
        return Polynomial3({index: -value
                            for index, value in self.coefficients.items()})

    def __sub__(self, other):
        return self + (-other)

    def __rsub__(self, other):
        return Polynomial3.constant(other) - self

    def __mul__(self, other):
        if not isinstance(other, Polynomial3):
            other = Polynomial3.constant(other)
        coefficients = {}
        for (i, j, k), left in self.coefficients.items():
            for (p, q, r), right in other.coefficients.items():
                index = (i + p, j + q, k + r)
                coefficients[index] = coefficients.get(
                    index, Interval(0)) + left * right
        return Polynomial3(coefficients)

    __rmul__ = __mul__

    def __pow__(self, exponent):
        result = Polynomial3.constant(1)
        base = self
        while exponent:
            if exponent & 1:
                result = result * base
            base = base * base
            exponent //= 2
        return result


U = Polynomial3({(1, 0, 0): Interval(1)})
V = Polynomial3({(0, 1, 0): Interval(1)})
W = Polynomial3({(0, 0, 1): Interval(1)})


def _evaluate_formula(text, values):
    """Evaluate a controlled arithmetic expression by exact intervals."""

    def visit(node):
        if isinstance(node, ast.Expression):
            return visit(node.body)
        if isinstance(node, ast.Constant) and isinstance(node.value, int):
            return Interval(node.value)
        if isinstance(node, ast.Name) and node.id in values:
            return values[node.id]
        if isinstance(node, ast.UnaryOp) and isinstance(node.op, ast.USub):
            return -visit(node.operand)
        if isinstance(node, ast.BinOp):
            left = visit(node.left)
            if isinstance(node.op, ast.Pow):
                if not (isinstance(node.right, ast.Constant)
                        and isinstance(node.right.value, int)
                        and node.right.value >= 0):
                    raise ValueError("formula exponent is not nonnegative")
                return left ** node.right.value
            right = visit(node.right)
            if isinstance(node.op, ast.Add):
                return left + right
            if isinstance(node.op, ast.Sub):
                return left - right
            if isinstance(node.op, ast.Mult):
                return left * right
            if isinstance(node.op, ast.Div):
                return left / right
        raise ValueError(f"unsupported formula syntax: {ast.dump(node)}")

    return visit(ast.parse(text, mode="eval"))


def _powers(polynomial, degree):
    output = [Polynomial3.constant(1)]
    for _ in range(degree):
        output.append(output[-1] * polynomial)
    return output


def _compose(polynomial_coefficients, vertices, degree):
    affine = []
    for coordinate in range(3):
        affine.append(
            Polynomial3.constant(vertices[0][coordinate])
            + U * (vertices[1][coordinate] - vertices[0][coordinate])
            + V * (vertices[2][coordinate] - vertices[0][coordinate])
            + W * (vertices[3][coordinate] - vertices[0][coordinate])
        )
    affine_powers = [_powers(value, degree) for value in affine]
    output = Polynomial3()
    for item in polynomial_coefficients:
        i, j, k = item["powers"]
        output += (affine_powers[0][i]
                   * affine_powers[1][j]
                   * affine_powers[2][k]
                   * item["value"])
    return output


def _bernstein_coefficients(polynomial, degree):
    output = {}
    for i in range(degree + 1):
        for j in range(degree + 1 - i):
            for k in range(degree + 1 - i - j):
                ell = degree - i - j - k
                value = Interval(0)
                for (p, q, r), coefficient in polynomial.coefficients.items():
                    if i >= p and j >= q and k >= r:
                        denominator = (
                            math.comb(degree, p + q + r)
                            * math.factorial(p + q + r)
                            // (math.factorial(p)
                                * math.factorial(q)
                                * math.factorial(r))
                        )
                        multiplier = Fraction(
                            math.comb(i, p) * math.comb(j, q)
                            * math.comb(k, r),
                            denominator,
                        )
                        value += coefficient * multiplier
                output[(i, j, k, ell)] = value
    return output


def _fraction_record(value):
    return {
        "numerator": str(value.numerator),
        "denominator": str(value.denominator),
        "decimal": f"{float(value):.12e}",
    }


def _interval_record(value):
    return {
        "lower": _fraction_record(value.lower),
        "upper": _fraction_record(value.upper),
    }


def _load_structure():
    raw = STRUCTURE_PATH.read_bytes()
    structure = json.loads(raw)
    if structure.get("schema_version") != 1:
        raise ValueError("unexpected n=4 structure schema")
    return structure, hashlib.sha256(raw).hexdigest()


def _vertices(structure, values):
    return {
        name: tuple(_evaluate_formula(formula, values)
                    for formula in formulas)
        for name, formulas in structure["vertex_formulas"].items()
    }


def certify_level(alpha_text, structure):
    brackets = exact_binomial_factor_brackets(
        4, alpha_text, FACTOR_BITS)
    p = [Interval(lower, upper) for lower, upper in brackets]

    # Weights of the normalized knots (0,x,y,z,1).
    a = 1 - p[3]
    b = p[3] - p[2]
    c = p[2] - p[1]
    d = p[1] - p[0]
    e = p[0]
    for name, weight in zip("abcde", (a, b, c, d, e)):
        if weight.lower <= 0:
            raise AssertionError(f"weight {name} is not positive")

    values = {"b": b, "c": c, "d": d, "e": e}
    vertices = _vertices(structure, values)

    # Region D (s <= x): weighted AM--GM requires b,c,d <= p_3/4.
    g = p[3]
    region_d_margins = {
        "p3_over_4_minus_b": g / 4 - b,
        "p3_over_4_minus_c": g / 4 - c,
        "p3_over_4_minus_d": g / 4 - d,
    }
    if any(value.lower <= 0 for value in region_d_margins.values()):
        raise AssertionError("region-D AM--GM condition is not certified")

    region_records = {}
    global_minimum = None
    for region_name in ("A", "B", "C"):
        region = structure["regions"][region_name]
        degree = region["degree"]
        polynomial_coefficients = [
            {
                "powers": item["powers"],
                "value": _evaluate_formula(item["expression"], values),
            }
            for item in region["polynomial_coefficients"]
        ]
        tetrahedron_records = []
        for tetrahedron in region["tetrahedra"]:
            transformed = _compose(
                polynomial_coefficients,
                [vertices[name] for name in tetrahedron["vertices"]],
                degree,
            )
            coefficients = _bernstein_coefficients(transformed, degree)
            zero_indices = {
                tuple(index)
                for index in tetrahedron["structural_zero_indices"]
            }
            for index in zero_indices:
                enclosure = coefficients[index]
                if not enclosure.lower <= 0 <= enclosure.upper:
                    raise AssertionError(
                        f"region {region_name} structural-zero enclosure "
                        f"{index} does not contain zero")
            positive = {
                index: value for index, value in coefficients.items()
                if index not in zero_indices
            }
            minimum_index, minimum = min(
                positive.items(), key=lambda item: item[1].lower)
            if minimum.lower <= 0:
                raise AssertionError(
                    f"region {region_name} coefficient {minimum_index} "
                    f"is not certified positive: {minimum}")
            if global_minimum is None or minimum.lower < global_minimum.lower:
                global_minimum = minimum
            tetrahedron_records.append({
                "vertices": tetrahedron["vertices"],
                "degree": degree,
                "coefficient_count": len(coefficients),
                "structural_zero_count": len(zero_indices),
                "minimum_positive_index": list(minimum_index),
                "minimum_positive_coefficient": _interval_record(minimum),
            })
        region_records[region_name] = {
            "alpha_identity": region["alpha_identity"],
            "extracted_nonnegative_factors":
                region["extracted_nonnegative_factors"],
            "tetrahedra": tetrahedron_records,
        }

    return {
        "alpha": alpha_text,
        "nominal_confidence": str(1 - Fraction(alpha_text)),
        "factor_bits": FACTOR_BITS,
        "factor_brackets": [_interval_record(value) for value in p],
        "weight_brackets": {
            name: _interval_record(value)
            for name, value in zip("abcde", (a, b, c, d, e))
        },
        "region_d_am_gm_margins": {
            name: _interval_record(value)
            for name, value in region_d_margins.items()
        },
        "polynomial_regions": region_records,
        "minimum_positive_bernstein_coefficient":
            _interval_record(global_minimum),
        "conclusion": (
            "For n=4 at this alpha, the binomial Stringer bound "
            "pointwise dominates the one-sided Gaffke bound."
        ),
    }


def build_certificate():
    structure, structure_sha256 = _load_structure()
    return {
        "schema_version": 1,
        "claim": (
            "At n=4 and nominal confidence 90%, 95%, or 99%, the "
            "binomial-factor Stringer bound pointwise dominates the "
            "one-sided Gaffke bound and is therefore distribution-free "
            "conservative under independent sampling."
        ),
        "arithmetic": (
            "Exact rational interval arithmetic; Clopper--Pearson factor "
            "brackets have integer-checked dyadic endpoint signs."
        ),
        "structure_file": str(STRUCTURE_PATH.relative_to(HERE.parents[2])),
        "structure_sha256": structure_sha256,
        "levels": [certify_level(alpha, structure) for alpha in ALPHAS],
    }


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path,
                        help="write the machine-readable certificate")
    args = parser.parse_args(argv)
    certificate = build_certificate()
    rendered = json.dumps(certificate, indent=2, sort_keys=True) + "\n"
    if args.out:
        args.out.write_text(rendered)
    for level in certificate["levels"]:
        minimum = level["minimum_positive_bernstein_coefficient"]
        print(
            f"alpha={level['alpha']}: certified; "
            f"minimum positive Bernstein lower bound="
            f"{minimum['lower']['decimal']}"
        )
    print("n4_gaffke_certificate: all exact sign checks passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
