"""Exact sign certificate for conventional-level Stringer coverage at ``n=5``.

For ``alpha`` equal to 0.01, 0.05, or 0.10, this module evaluates the exact
polynomial/four-simplex structure generated by
:mod:`derive_n5_bernstein_structure`.  Clopper--Pearson roots are enclosed by
dyadic rationals with integer-checked binomial-CDF signs, and every remaining
operation uses integer-directed dyadic interval arithmetic. Floating point
is used only to print readable summaries.
"""

from __future__ import annotations

import argparse
import ast
import hashlib
import itertools
import json
import math
from fractions import Fraction
from pathlib import Path

from stringer import exact_binomial_factor_brackets


ALPHAS = ("0.01", "0.05", "0.10")
FACTOR_BITS = 240
INTERVAL_BITS = 256
INTERVAL_SCALE = 1 << INTERVAL_BITS
HERE = Path(__file__).resolve().parent
CERTIFICATE_DIR = HERE.parent / "certificates"
STRUCTURE_PATH = CERTIFICATE_DIR / "n5-gaffke-bernstein-structure.json"
DIMENSION = 4


class Interval:
    """Closed dyadic interval with integer-directed outward rounding.

    Both endpoints are stored as integer multiples of ``2^-INTERVAL_BITS``.
    Addition is exact on that grid. Multiplication and reciprocal round the
    lower endpoint down and the upper endpoint up using integer division.
    This avoids the denominator growth of unrestricted ``Fraction``
    arithmetic while retaining proof-grade enclosures.
    """

    __slots__ = ("_lower", "_upper")

    def __init__(self, lower=0, upper=None):
        if isinstance(lower, Interval):
            self._lower = lower._lower
            self._upper = lower._upper
            return
        lo = Fraction(lower)
        hi = lo if upper is None else Fraction(upper)
        if lo > hi:
            raise ValueError("interval endpoints are reversed")
        self._lower = _floor_fraction_scaled(lo)
        self._upper = _ceil_fraction_scaled(hi)

    @classmethod
    def _from_scaled(cls, lower, upper):
        result = object.__new__(cls)
        result._lower = lower
        result._upper = upper
        return result

    @property
    def lower(self):
        return Fraction(self._lower, INTERVAL_SCALE)

    @property
    def upper(self):
        return Fraction(self._upper, INTERVAL_SCALE)

    def __add__(self, other):
        if isinstance(other, SimplexPolynomial):
            return NotImplemented
        other = Interval(other)
        return Interval._from_scaled(
            self._lower + other._lower,
            self._upper + other._upper,
        )

    __radd__ = __add__

    def __neg__(self):
        return Interval._from_scaled(-self._upper, -self._lower)

    def __sub__(self, other):
        if isinstance(other, SimplexPolynomial):
            return NotImplemented
        return self + (-Interval(other))

    def __rsub__(self, other):
        return Interval(other) - self

    def __mul__(self, other):
        if isinstance(other, SimplexPolynomial):
            return NotImplemented
        other = Interval(other)
        products = (
            self._lower * other._lower,
            self._lower * other._upper,
            self._upper * other._lower,
            self._upper * other._upper,
        )
        return Interval._from_scaled(
            min(products) // INTERVAL_SCALE,
            _ceil_div(max(products), INTERVAL_SCALE),
        )

    __rmul__ = __mul__

    def reciprocal(self):
        if self._lower <= 0 <= self._upper:
            raise ZeroDivisionError("interval contains zero")
        scale_squared = INTERVAL_SCALE * INTERVAL_SCALE
        return Interval._from_scaled(
            scale_squared // self._upper,
            _ceil_div(scale_squared, self._lower),
        )

    def __truediv__(self, other):
        return self * Interval(other).reciprocal()

    def __rtruediv__(self, other):
        return Interval(other) / self

    def __pow__(self, exponent):
        result = Interval(1)
        base = self
        while exponent:
            if exponent & 1:
                result = result * base
            base = base * base
            exponent //= 2
        return result


def _ceil_div(numerator, denominator):
    """Return the mathematical ceiling of an integer ratio."""

    return -((-numerator) // denominator)


def _floor_fraction_scaled(value):
    return (value.numerator * INTERVAL_SCALE) // value.denominator


def _ceil_fraction_scaled(value):
    return _ceil_div(
        value.numerator * INTERVAL_SCALE, value.denominator)


class SimplexPolynomial:
    """Sparse polynomial in four standard-simplex coordinates."""

    def __init__(self, coefficients=None):
        self.coefficients = {}
        for index, value in (coefficients or {}).items():
            value = Interval(value)
            if value._lower != 0 or value._upper != 0:
                self.coefficients[index] = value

    @classmethod
    def constant(cls, value):
        return cls({(0,) * DIMENSION: Interval(value)})

    def __add__(self, other):
        if not isinstance(other, SimplexPolynomial):
            other = SimplexPolynomial.constant(other)
        coefficients = dict(self.coefficients)
        for index, value in other.coefficients.items():
            coefficients[index] = coefficients.get(
                index, Interval(0)) + value
        return SimplexPolynomial(coefficients)

    __radd__ = __add__

    def __neg__(self):
        return SimplexPolynomial({
            index: -value for index, value in self.coefficients.items()
        })

    def __sub__(self, other):
        return self + (-other)

    def __rsub__(self, other):
        return SimplexPolynomial.constant(other) - self

    def __mul__(self, other):
        if not isinstance(other, SimplexPolynomial):
            other = SimplexPolynomial.constant(other)
        coefficients = {}
        for left_index, left in self.coefficients.items():
            for right_index, right in other.coefficients.items():
                index = tuple(a + b for a, b in zip(
                    left_index, right_index))
                coefficients[index] = coefficients.get(
                    index, Interval(0)) + left * right
        return SimplexPolynomial(coefficients)

    __rmul__ = __mul__

    def __pow__(self, exponent):
        result = SimplexPolynomial.constant(1)
        base = self
        while exponent:
            if exponent & 1:
                result = result * base
            base = base * base
            exponent //= 2
        return result


STANDARD_COORDINATES = [
    SimplexPolynomial({
        tuple(1 if coordinate == index else 0
              for coordinate in range(DIMENSION)): Interval(1)
    })
    for index in range(DIMENSION)
]


def _evaluate_formula(text, values):
    """Evaluate a controlled arithmetic expression by exact intervals."""

    def visit(node):
        if isinstance(node, ast.Expression):
            return visit(node.body)
        if isinstance(node, ast.Constant) and isinstance(node.value, int):
            return Interval(node.value)
        if isinstance(node, ast.Name) and node.id in values:
            return values[node.id]
        if isinstance(node, ast.UnaryOp) and isinstance(node.op, ast.USub):
            return -visit(node.operand)
        if isinstance(node, ast.BinOp):
            left = visit(node.left)
            if isinstance(node.op, ast.Pow):
                if not (isinstance(node.right, ast.Constant)
                        and isinstance(node.right.value, int)
                        and node.right.value >= 0):
                    raise ValueError("formula exponent is not nonnegative")
                return left ** node.right.value
            right = visit(node.right)
            if isinstance(node.op, ast.Add):
                return left + right
            if isinstance(node.op, ast.Sub):
                return left - right
            if isinstance(node.op, ast.Mult):
                return left * right
            if isinstance(node.op, ast.Div):
                return left / right
        raise ValueError(f"unsupported formula syntax: {ast.dump(node)}")

    return visit(ast.parse(text, mode="eval"))


def _powers(polynomial, degree):
    output = [SimplexPolynomial.constant(1)]
    for _ in range(degree):
        output.append(output[-1] * polynomial)
    return output


def _compose(polynomial_coefficients, vertices, degree):
    affine = []
    for coordinate in range(DIMENSION):
        value = SimplexPolynomial.constant(vertices[0][coordinate])
        for index, standard_coordinate in enumerate(STANDARD_COORDINATES):
            value += standard_coordinate * (
                vertices[index + 1][coordinate]
                - vertices[0][coordinate]
            )
        affine.append(value)
    affine_powers = [_powers(value, degree) for value in affine]
    output = SimplexPolynomial()
    for item in polynomial_coefficients:
        term = SimplexPolynomial.constant(item["value"])
        for coordinate, exponent in enumerate(item["powers"]):
            term *= affine_powers[coordinate][exponent]
        output += term
    return output


def _bernstein_indices(degree):
    for i in range(degree + 1):
        for j in range(degree + 1 - i):
            for k in range(degree + 1 - i - j):
                for ell in range(degree + 1 - i - j - k):
                    yield (i, j, k, ell,
                           degree - i - j - k - ell)


def _bernstein_coefficients(polynomial, degree):
    output = {}
    for index in _bernstein_indices(degree):
        simplex_index = index[:DIMENSION]
        value = Interval(0)
        for powers, coefficient in polynomial.coefficients.items():
            if all(i >= p for i, p in zip(simplex_index, powers)):
                total = sum(powers)
                denominator = (
                    math.factorial(degree)
                    // math.factorial(degree - total)
                )
                for exponent in powers:
                    denominator //= math.factorial(exponent)
                numerator = math.prod(
                    math.comb(i, p)
                    for i, p in zip(simplex_index, powers)
                )
                value += coefficient * Fraction(numerator, denominator)
        output[index] = value
    return output


def _fraction_record(value):
    return {
        "numerator": str(value.numerator),
        "denominator": str(value.denominator),
        "decimal": f"{float(value):.12e}",
    }


def _interval_record(value):
    return {
        "lower": _fraction_record(value.lower),
        "upper": _fraction_record(value.upper),
    }


def _load_structure():
    raw = STRUCTURE_PATH.read_bytes()
    structure = json.loads(raw)
    if structure.get("schema_version") != 1:
        raise ValueError("unexpected n=5 structure schema")
    return structure, hashlib.sha256(raw).hexdigest()


def _vertices(structure, values):
    return {
        name: tuple(_evaluate_formula(formula, values)
                    for formula in formulas)
        for name, formulas in structure["vertex_formulas"].items()
    }


def _permutation_sign(permutation):
    inversions = sum(
        permutation[i] > permutation[j]
        for i in range(len(permutation))
        for j in range(i + 1, len(permutation))
    )
    return -1 if inversions % 2 else 1


def _simplex_determinant(vertices):
    """Exact interval enclosure of the affine four-simplex determinant."""

    matrix = [
        [vertices[column + 1][row] - vertices[0][row]
         for column in range(DIMENSION)]
        for row in range(DIMENSION)
    ]
    determinant = Interval(0)
    for permutation in itertools.permutations(range(DIMENSION)):
        term = Interval(_permutation_sign(permutation))
        for row, column in enumerate(permutation):
            term *= matrix[row][column]
        determinant += term
    return determinant


def certify_level(alpha_text, structure):
    brackets = exact_binomial_factor_brackets(
        5, alpha_text, FACTOR_BITS)
    p = [Interval(lower, upper) for lower, upper in brackets]

    a = 1 - p[4]
    b = p[4] - p[3]
    c = p[3] - p[2]
    d = p[2] - p[1]
    e = p[1] - p[0]
    f = p[0]
    for name, weight in zip("abcdef", (a, b, c, d, e, f)):
        if weight.lower <= 0:
            raise AssertionError(f"weight {name} is not positive")

    values = {name: value for name, value in zip(
        "bcdef", (b, c, d, e, f))}
    vertices = _vertices(structure, values)

    region_records = {}
    global_minimum = None
    for region_name in ("A", "B", "C", "D", "E"):
        print(f"alpha={alpha_text}: certifying region {region_name}",
              flush=True)
        region = structure["regions"][region_name]
        degree = region["degree"]
        polynomial_coefficients = [
            {
                "powers": item["powers"],
                "value": _evaluate_formula(item["expression"], values),
            }
            for item in region["polynomial_coefficients"]
        ]
        simplex_records = []
        for simplex in region["simplices"]:
            simplex_vertices = [
                vertices[name] for name in simplex["vertices"]
            ]
            determinant = _simplex_determinant(simplex_vertices)
            if determinant.lower <= 0 <= determinant.upper:
                raise AssertionError(
                    f"region {region_name} simplex is not certified "
                    f"nondegenerate: {simplex['vertices']}")
            transformed = _compose(
                polynomial_coefficients,
                simplex_vertices,
                degree,
            )
            coefficients = _bernstein_coefficients(transformed, degree)
            zero_indices = {
                tuple(index) for index in simplex["structural_zero_indices"]
            }
            for index in zero_indices:
                enclosure = coefficients[index]
                if not enclosure.lower <= 0 <= enclosure.upper:
                    raise AssertionError(
                        f"region {region_name} structural-zero enclosure "
                        f"{index} does not contain zero")
            positive = {
                index: value for index, value in coefficients.items()
                if index not in zero_indices
            }
            minimum_index, minimum = min(
                positive.items(), key=lambda item: item[1].lower)
            if minimum.lower <= 0:
                raise AssertionError(
                    f"region {region_name} coefficient {minimum_index} "
                    f"is not certified positive: {minimum}")
            if global_minimum is None or minimum.lower < global_minimum.lower:
                global_minimum = minimum
            simplex_records.append({
                "vertices": simplex["vertices"],
                "degree": degree,
                "coefficient_count": len(coefficients),
                "structural_zero_count": len(zero_indices),
                "affine_determinant": _interval_record(determinant),
                "minimum_positive_index": list(minimum_index),
                "minimum_positive_coefficient": _interval_record(minimum),
            })
        region_records[region_name] = {
            "alpha_identity": region["alpha_identity"],
            "extracted_nonnegative_factors":
                region["extracted_nonnegative_factors"],
            "simplices": simplex_records,
        }

    return {
        "alpha": alpha_text,
        "nominal_confidence": str(1 - Fraction(alpha_text)),
        "factor_bits": FACTOR_BITS,
        "interval_bits": INTERVAL_BITS,
        "factor_brackets": [_interval_record(value) for value in p],
        "weight_brackets": {
            name: _interval_record(value)
            for name, value in zip("abcdef", (a, b, c, d, e, f))
        },
        "polynomial_regions": region_records,
        "minimum_positive_bernstein_coefficient":
            _interval_record(global_minimum),
        "conclusion": (
            "For n=5 at this alpha, the binomial Stringer bound "
            "pointwise dominates the one-sided Gaffke bound."
        ),
    }


def build_certificate():
    structure, structure_sha256 = _load_structure()
    if structure.get("face_order_verification") != (
            "exact_polynomial_ideal_membership"):
        raise ValueError(
            "n=5 structure lacks exact face-order verification")
    return {
        "schema_version": 1,
        "claim": (
            "At n=5 and nominal confidence 90%, 95%, or 99%, the "
            "binomial-factor Stringer bound pointwise dominates the "
            "one-sided Gaffke bound and is therefore distribution-free "
            "conservative under independent sampling."
        ),
        "arithmetic": (
            "Integer-directed dyadic interval arithmetic with exact outward "
            f"rounding at {INTERVAL_BITS} fractional bits; Clopper--Pearson "
            "factor brackets have integer-checked dyadic endpoint signs."
        ),
        "structure_file": str(STRUCTURE_PATH.relative_to(HERE.parents[2])),
        "structure_sha256": structure_sha256,
        "levels": [certify_level(alpha, structure) for alpha in ALPHAS],
    }


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path,
                        help="write the machine-readable certificate")
    parser.add_argument(
        "--allow-unverified-structure", action="store_true",
        help="development only: accept a structure made with --skip-face-proof",
    )
    args = parser.parse_args(argv)
    structure, _ = _load_structure()
    if (structure.get("face_order_verification") !=
            "exact_polynomial_ideal_membership"):
        if not args.allow_unverified_structure:
            raise ValueError("n=5 structure lacks exact face proof")
        # Development path; build_certificate intentionally rejects this.
        original = structure["face_order_verification"]
        structure["face_order_verification"] = (
            "exact_polynomial_ideal_membership")
        certificate = {
            "schema_version": 0,
            "development_only": True,
            "original_face_order_verification": original,
            "levels": [certify_level(alpha, structure) for alpha in ALPHAS],
        }
    else:
        certificate = build_certificate()
    rendered = json.dumps(certificate, indent=2, sort_keys=True) + "\n"
    if args.out:
        args.out.write_text(rendered)
    for level in certificate["levels"]:
        minimum = level["minimum_positive_bernstein_coefficient"]
        print(
            f"alpha={level['alpha']}: certified; "
            f"minimum positive Bernstein lower bound="
            f"{minimum['lower']['decimal']}"
        )
    print("n5_gaffke_certificate: all exact sign checks passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
