"""Exact sign certificate for conventional-level Stringer coverage at ``n=6``.

For ``alpha`` in ``{0.01, 0.05, 0.10}``, this module evaluates the exact
polynomial/five-simplex structure generated by
:mod:`derive_n6_bernstein_structure`.
Clopper--Pearson roots are enclosed by
dyadic rationals with integer-checked binomial-CDF signs, and every remaining
operation uses integer-directed dyadic interval arithmetic. Floating point
is used only to print readable summaries.
"""

from __future__ import annotations

import argparse
import ast
import hashlib
import itertools
import json
import math
import multiprocessing as mp
import os
from fractions import Fraction
from pathlib import Path

from stringer import exact_binomial_factor_brackets


ALPHAS = ("0.01", "0.05", "0.10")
FACTOR_BITS = 320
INTERVAL_BITS = 384
INTERVAL_SCALE = 1 << INTERVAL_BITS
HERE = Path(__file__).resolve().parent
CERTIFICATE_DIR = HERE.parent / "certificates"
STRUCTURE_PATH = CERTIFICATE_DIR / "n6-gaffke-bernstein-structure.json"
DEFAULT_CERTIFICATE_PATH = CERTIFICATE_DIR / "n6-gaffke-certificate.json"
DIMENSION = 5


class Interval:
    """Closed dyadic interval with integer-directed outward rounding.

    Both endpoints are stored as integer multiples of ``2^-INTERVAL_BITS``.
    Addition is exact on that grid. Multiplication and reciprocal round the
    lower endpoint down and the upper endpoint up using integer division.
    This avoids the denominator growth of unrestricted ``Fraction``
    arithmetic while retaining proof-grade enclosures.
    """

    __slots__ = ("_lower", "_upper")

    def __init__(self, lower=0, upper=None):
        if isinstance(lower, Interval):
            self._lower = lower._lower
            self._upper = lower._upper
            return
        lo = Fraction(lower)
        hi = lo if upper is None else Fraction(upper)
        if lo > hi:
            raise ValueError("interval endpoints are reversed")
        self._lower = _floor_fraction_scaled(lo)
        self._upper = _ceil_fraction_scaled(hi)

    @classmethod
    def _from_scaled(cls, lower, upper):
        result = object.__new__(cls)
        result._lower = lower
        result._upper = upper
        return result

    @property
    def lower(self):
        return Fraction(self._lower, INTERVAL_SCALE)

    @property
    def upper(self):
        return Fraction(self._upper, INTERVAL_SCALE)

    def __add__(self, other):
        if isinstance(other, SimplexPolynomial):
            return NotImplemented
        other = Interval(other)
        return Interval._from_scaled(
            self._lower + other._lower,
            self._upper + other._upper,
        )

    __radd__ = __add__

    def __neg__(self):
        return Interval._from_scaled(-self._upper, -self._lower)

    def __sub__(self, other):
        if isinstance(other, SimplexPolynomial):
            return NotImplemented
        return self + (-Interval(other))

    def __rsub__(self, other):
        return Interval(other) - self

    def __mul__(self, other):
        if isinstance(other, SimplexPolynomial):
            return NotImplemented
        if not isinstance(other, Interval):
            scalar = Fraction(other)
            if scalar >= 0:
                lower_product = self._lower * scalar.numerator
                upper_product = self._upper * scalar.numerator
            else:
                lower_product = self._upper * scalar.numerator
                upper_product = self._lower * scalar.numerator
            denominator = scalar.denominator
            if denominator & (denominator - 1) == 0:
                shift = denominator.bit_length() - 1
                lower = lower_product >> shift
                upper = -((-upper_product) >> shift)
            else:
                lower = lower_product // denominator
                upper = _ceil_div(upper_product, denominator)
            return Interval._from_scaled(lower, upper)
        other = Interval(other)
        products = (
            self._lower * other._lower,
            self._lower * other._upper,
            self._upper * other._lower,
            self._upper * other._upper,
        )
        return Interval._from_scaled(
            min(products) // INTERVAL_SCALE,
            _ceil_div(max(products), INTERVAL_SCALE),
        )

    __rmul__ = __mul__

    def reciprocal(self):
        if self._lower <= 0 <= self._upper:
            raise ZeroDivisionError("interval contains zero")
        scale_squared = INTERVAL_SCALE * INTERVAL_SCALE
        return Interval._from_scaled(
            scale_squared // self._upper,
            _ceil_div(scale_squared, self._lower),
        )

    def __truediv__(self, other):
        return self * Interval(other).reciprocal()

    def __rtruediv__(self, other):
        return Interval(other) / self

    def __pow__(self, exponent):
        result = Interval(1)
        base = self
        while exponent:
            if exponent & 1:
                result = result * base
            base = base * base
            exponent //= 2
        return result


def _ceil_div(numerator, denominator):
    """Return the mathematical ceiling of an integer ratio."""

    return -((-numerator) // denominator)


def _floor_fraction_scaled(value):
    return (value.numerator * INTERVAL_SCALE) // value.denominator


def _ceil_fraction_scaled(value):
    return _ceil_div(
        value.numerator * INTERVAL_SCALE, value.denominator)


class SimplexPolynomial:
    """Sparse polynomial in five standard-simplex coordinates."""

    def __init__(self, coefficients=None):
        self.coefficients = {}
        for index, value in (coefficients or {}).items():
            value = Interval(value)
            if value._lower != 0 or value._upper != 0:
                self.coefficients[index] = value

    @classmethod
    def constant(cls, value):
        return cls({(0,) * DIMENSION: Interval(value)})

    def __add__(self, other):
        if not isinstance(other, SimplexPolynomial):
            other = SimplexPolynomial.constant(other)
        coefficients = dict(self.coefficients)
        for index, value in other.coefficients.items():
            coefficients[index] = coefficients.get(
                index, Interval(0)) + value
        return SimplexPolynomial(coefficients)

    __radd__ = __add__

    def __neg__(self):
        return SimplexPolynomial({
            index: -value for index, value in self.coefficients.items()
        })

    def __sub__(self, other):
        return self + (-other)

    def __rsub__(self, other):
        return SimplexPolynomial.constant(other) - self

    def __mul__(self, other):
        if not isinstance(other, SimplexPolynomial):
            other = SimplexPolynomial.constant(other)
        coefficients = {}
        for left_index, left in self.coefficients.items():
            for right_index, right in other.coefficients.items():
                index = tuple(a + b for a, b in zip(
                    left_index, right_index))
                coefficients[index] = coefficients.get(
                    index, Interval(0)) + left * right
        return SimplexPolynomial(coefficients)

    __rmul__ = __mul__

    def __pow__(self, exponent):
        result = SimplexPolynomial.constant(1)
        base = self
        while exponent:
            if exponent & 1:
                result = result * base
            base = base * base
            exponent //= 2
        return result


STANDARD_COORDINATES = [
    SimplexPolynomial({
        tuple(1 if coordinate == index else 0
              for coordinate in range(DIMENSION)): Interval(1)
    })
    for index in range(DIMENSION)
]


def _evaluate_formula(text, values):
    """Evaluate a controlled arithmetic expression by exact intervals."""

    def visit(node):
        if isinstance(node, ast.Expression):
            return visit(node.body)
        if isinstance(node, ast.Constant) and isinstance(node.value, int):
            return Interval(node.value)
        if isinstance(node, ast.Name) and node.id in values:
            return values[node.id]
        if isinstance(node, ast.UnaryOp) and isinstance(node.op, ast.USub):
            return -visit(node.operand)
        if isinstance(node, ast.BinOp):
            left = visit(node.left)
            if isinstance(node.op, ast.Pow):
                if not (isinstance(node.right, ast.Constant)
                        and isinstance(node.right.value, int)
                        and node.right.value >= 0):
                    raise ValueError("formula exponent is not nonnegative")
                return left ** node.right.value
            right = visit(node.right)
            if isinstance(node.op, ast.Add):
                return left + right
            if isinstance(node.op, ast.Sub):
                return left - right
            if isinstance(node.op, ast.Mult):
                return left * right
            if isinstance(node.op, ast.Div):
                return left / right
        raise ValueError(f"unsupported formula syntax: {ast.dump(node)}")

    return visit(ast.parse(text, mode="eval"))


def _powers(polynomial, degree):
    output = [SimplexPolynomial.constant(1)]
    for _ in range(degree):
        output.append(output[-1] * polynomial)
    return output


def _compose(polynomial_coefficients, vertices, degree):
    affine = []
    for coordinate in range(DIMENSION):
        value = SimplexPolynomial.constant(vertices[0][coordinate])
        for index, standard_coordinate in enumerate(STANDARD_COORDINATES):
            value += standard_coordinate * (
                vertices[index + 1][coordinate]
                - vertices[0][coordinate]
            )
        affine.append(value)
    affine_powers = [_powers(value, degree) for value in affine]
    output = SimplexPolynomial()
    for item in polynomial_coefficients:
        term = SimplexPolynomial.constant(item["value"])
        for coordinate, exponent in enumerate(item["powers"]):
            term *= affine_powers[coordinate][exponent]
        output += term
    return output


def _bernstein_indices(degree):
    for prefix in itertools.product(range(degree + 1), repeat=DIMENSION):
        if sum(prefix) <= degree:
            yield prefix + (degree - sum(prefix),)


def _bernstein_coefficients(polynomial, degree):
    # Iterate only over comparable power/Bernstein multi-index pairs.
    # The inverse loop over every pair is quadratic in C(degree+5,5): at
    # degree 12 it performs 38 million dominance tests per simplex, versus
    # 646,646 actual contributions here. Addition on the fixed dyadic grid
    # is exact, so changing the accumulation order does not change an
    # enclosure endpoint.
    output = {index: Interval(0) for index in _bernstein_indices(degree)}
    for powers, coefficient in polynomial.coefficients.items():
        total = sum(powers)
        remaining = degree - total
        if remaining < 0:
            raise ValueError("power-basis term exceeds Bernstein degree")
        denominator = (
            math.factorial(degree)
            // math.factorial(remaining)
        )
        for exponent in powers:
            denominator //= math.factorial(exponent)
        for increment in _bernstein_indices(remaining):
            simplex_index = tuple(
                power + delta
                for power, delta in zip(powers, increment[:DIMENSION])
            )
            numerator = math.prod(
                math.comb(index, power)
                for index, power in zip(simplex_index, powers)
            )
            full_index = simplex_index + (
                degree - sum(simplex_index),
            )
            output[full_index] += coefficient * Fraction(
                numerator, denominator)
    return output


def _fraction_record(value):
    return {
        "numerator": str(value.numerator),
        "denominator": str(value.denominator),
        "decimal": f"{float(value):.12e}",
    }


def _interval_record(value):
    return {
        "lower": _fraction_record(value.lower),
        "upper": _fraction_record(value.upper),
    }


def _load_structure():
    raw = STRUCTURE_PATH.read_bytes()
    structure = json.loads(raw)
    if structure.get("schema_version") != 1:
        raise ValueError("unexpected n=6 structure schema")
    return structure, hashlib.sha256(raw).hexdigest()


def _vertices(structure, values):
    return {
        name: tuple(_evaluate_formula(formula, values)
                    for formula in formulas)
        for name, formulas in structure["vertex_formulas"].items()
    }


def _permutation_sign(permutation):
    inversions = sum(
        permutation[i] > permutation[j]
        for i in range(len(permutation))
        for j in range(i + 1, len(permutation))
    )
    return -1 if inversions % 2 else 1


def _simplex_determinant(vertices):
    """Exact interval enclosure of the affine five-simplex determinant."""

    matrix = [
        [vertices[column + 1][row] - vertices[0][row]
         for column in range(DIMENSION)]
        for row in range(DIMENSION)
    ]
    return _matrix_determinant(matrix)


def _matrix_determinant(matrix):
    """Exact interval determinant of a square matrix."""

    dimension = len(matrix)
    if any(len(row) != dimension for row in matrix):
        raise ValueError("determinant matrix is not square")
    determinant = Interval(0)
    for permutation in itertools.permutations(range(dimension)):
        term = Interval(_permutation_sign(permutation))
        for row, column in enumerate(permutation):
            term *= matrix[row][column]
        determinant += term
    return determinant


DOMAIN_BOUNDARY_LABELS = (
    "x=0", "x=y", "y=z", "z=w", "w=u", "u=1",
)


def _vertex_forms(point, weights):
    """Return ordered-domain gaps and threshold differences at a vertex."""

    b, c, d, e, f, g = weights[1:]
    x, y, z, w, u = point
    s = b * x + c * y + d * z + e * w + f * u + g
    return {
        "x=0": x,
        "x=y": y - x,
        "y=z": z - y,
        "z=w": w - z,
        "w=u": u - w,
        "u=1": 1 - u,
        "s=x": s - x,
        "s=y": s - y,
        "s=z": s - z,
        "s=w": s - w,
        "s=u": s - u,
    }


def _certify_region_vertices(region_name, region, vertices, identities,
                             weights):
    """Certify that every triangulation vertex lies in its cap region."""

    # Each listed expression must be nonnegative.  A minus sign reverses a
    # stored threshold difference.  Identically zero forms are established
    # in the exact structure layer; all other signs are proved by intervals.
    region_forms = {
        "A": (("s=u", 1),),
        "B": (("s=w", 1), ("s=u", -1)),
        "C": (("s=z", 1), ("s=w", -1)),
        "D": (("s=y", 1), ("s=z", -1)),
        "E": (("s=x", 1), ("s=y", -1)),
        "F": (("s=x", -1),),
    }[region_name]
    names = sorted({name for simplex in region["simplices"]
                    for name in simplex["vertices"]})
    checked = 0
    exact_zeros = 0
    minimum = None
    for name in names:
        forms = _vertex_forms(vertices[name], weights)
        checks = tuple((label, 1) for label in DOMAIN_BOUNDARY_LABELS)
        checks += region_forms
        for label, sign in checks:
            value = forms[label] if sign > 0 else -forms[label]
            if label in identities[name]:
                if not value.lower <= 0 <= value.upper:
                    raise AssertionError(
                        f"exact vertex identity {name}, {label} "
                        "is not enclosed at zero")
                exact_zeros += 1
            else:
                if value.lower <= 0:
                    raise AssertionError(
                        f"vertex {name} is not certified inside region "
                        f"{region_name} at {label}: {value.lower}")
                if minimum is None or value.lower < minimum.lower:
                    minimum = value
            checked += 1
    return {
        "vertex_count": len(names),
        "ordered_domain_and_region_inequalities_checked": checked,
        "exact_boundary_equalities_used": exact_zeros,
        "minimum_strict_vertex_slack": (
            _interval_record(minimum) if minimum is not None else None),
    }


def _certify_face_normal_ranks(structure, weights):
    """Certify specialization of every generic affine-face ideal.

    Generic differential reductions prove the face identities over the
    rational-function field in the weights. A nonzero normal minor at the
    certified weight intervals ensures that each selected affine generator
    set retains full rank when those generic identities are specialized.
    """

    b, c, d, e, f, _ = weights[1:]
    normal_rows = {
        "x=0": (1, 0, 0, 0, 0),
        "x=y": (-1, 1, 0, 0, 0),
        "y=z": (0, -1, 1, 0, 0),
        "z=w": (0, 0, -1, 1, 0),
        "w=u": (0, 0, 0, -1, 1),
        "u=1": (0, 0, 0, 0, -1),
        "s=x": (b - 1, c, d, e, f),
        "s=y": (b, c - 1, d, e, f),
        "s=z": (b, c, d - 1, e, f),
        "s=w": (b, c, d, e - 1, f),
        "s=u": (b, c, d, e, f - 1),
    }
    generator_sets = set()
    face_order_conditions = set()
    for region_name, region in structure["regions"].items():
        for simplex in region["simplices"]:
            for proof in simplex["face_order_proofs"]:
                labels = tuple(proof["independent_ideal_generators"])
                generator_sets.add(labels)
                face_order_conditions.add(
                    (region_name, labels, proof["vanishing_order"]))

    records = []
    minimum = None
    coordinate_names = ("x", "y", "z", "w", "u")
    for labels in sorted(generator_sets,
                         key=lambda value: (len(value), value)):
        dimension = len(labels)
        candidates = []
        for columns in itertools.combinations(range(DIMENSION), dimension):
            determinant = _matrix_determinant([
                [normal_rows[label][column] for column in columns]
                for label in labels
            ])
            if determinant.lower > 0:
                margin = determinant.lower
            elif determinant.upper < 0:
                margin = -determinant.upper
            else:
                continue
            candidates.append((margin, columns, determinant))
        if not candidates:
            raise AssertionError(
                f"face normals lose rank at certified weights: {labels}")
        margin, columns, determinant = max(
            candidates, key=lambda item: item[0])
        if minimum is None or margin < minimum:
            minimum = margin
        records.append({
            "independent_ideal_generators": list(labels),
            "minor_coordinate_columns": [
                coordinate_names[index] for index in columns
            ],
            "normal_minor_determinant": _interval_record(determinant),
        })
    return {
        "generator_sets_certified": len(records),
        "generic_region_face_order_checks_linked":
            len(face_order_conditions),
        "minimum_absolute_normal_minor": _fraction_record(minimum),
        "sets": records,
        "conclusion": (
            "Every affine generator set used by the generic differential "
            "ideal proof retains full normal rank at the certified weight "
            "intervals."
        ),
    }


def _permutation_sign_for_names(sequence, canonical):
    positions = [canonical.index(value) for value in sequence]
    return _permutation_sign(positions)


def _certify_global_chain(structure, region_records, vertices):
    """Certify that the 32 oriented simplices triangulate the full domain.

    The exact vertex labels make this an integer simplicial-chain check.
    Every internal facet must cancel, and every unpaired facet must lie on
    an outer ordered-simplex boundary.  The directed determinant sum then
    locates the relative-chain degree at the integer one.
    """

    distinct_pairs = 0
    for left, right in itertools.combinations(sorted(vertices), 2):
        if not any((vertices[left][coordinate] - vertices[right][coordinate]
                    ).lower > 0
                   or (vertices[left][coordinate]
                       - vertices[right][coordinate]).upper < 0
                   for coordinate in range(DIMENSION)):
            raise AssertionError(
                f"vertices are not certified distinct: {left}, {right}")
        distinct_pairs += 1

    incidences = {}
    total_determinant = Interval(0)
    simplex_count = 0
    for region_name in "ABCDEF":
        structure_simplices = structure["regions"][region_name]["simplices"]
        certified_simplices = region_records[region_name]["simplices"]
        for structure_simplex, certified in zip(
                structure_simplices, certified_simplices):
            names = structure_simplex["vertices"]
            determinant = certified["affine_determinant"]
            determinant = Interval(
                Fraction(int(determinant["lower"]["numerator"]),
                         int(determinant["lower"]["denominator"])),
                Fraction(int(determinant["upper"]["numerator"]),
                         int(determinant["upper"]["denominator"])),
            )
            orientation = certified["orientation_sign"]
            total_determinant += (determinant if orientation > 0
                                  else -determinant)
            for removed in range(DIMENSION + 1):
                raw_face = names[:removed] + names[removed + 1:]
                canonical = tuple(sorted(raw_face))
                coefficient = (
                    orientation * ((-1) ** removed)
                    * _permutation_sign_for_names(raw_face, canonical)
                )
                incidences.setdefault(canonical, []).append(coefficient)
            simplex_count += 1

    internal = 0
    boundary = 0
    boundary_counts = {label: 0 for label in DOMAIN_BOUNDARY_LABELS}
    identities = structure["vertex_boundary_identities"]
    for face, coefficients in incidences.items():
        if len(coefficients) == 2:
            if sum(coefficients) != 0:
                raise AssertionError(
                    f"oriented internal facet does not cancel: {face}")
            internal += 1
        elif len(coefficients) == 1:
            common = set(DOMAIN_BOUNDARY_LABELS)
            for vertex_name in face:
                common.intersection_update(identities[vertex_name])
            if not common:
                raise AssertionError(
                    f"unpaired facet is not on the outer boundary: {face}")
            # A nondegenerate four-face cannot lie in the intersection of
            # two distinct outer hyperplanes.
            if len(common) != 1:
                raise AssertionError(
                    f"unpaired facet has ambiguous outer boundary: "
                    f"{face}, {sorted(common)}")
            label = next(iter(common))
            boundary_counts[label] += 1
            boundary += 1
        else:
            raise AssertionError(
                f"facet incidence is not one or two: {face}, {coefficients}")

    if not (total_determinant.lower > Fraction(1, 2)
            and total_determinant.upper < Fraction(3, 2)):
        raise AssertionError(
            "oriented triangulation degree is not certified as one")
    return {
        "simplex_count": simplex_count,
        "distinct_vertex_pairs_certified": distinct_pairs,
        "internal_facets_paired_with_opposite_orientation": internal,
        "unpaired_outer_boundary_facets": boundary,
        "outer_boundary_facets_by_hyperplane": boundary_counts,
        "normalized_oriented_volume": _interval_record(total_determinant),
        "integer_relative_chain_degree": 1,
        "conclusion": (
            "The positively oriented simplices form a relative cycle of "
            "degree one and therefore cover the ordered knot simplex "
            "without interior multiplicity."
        ),
    }


_SIMPLEX_CONTEXT = None


def _certify_simplex(task):
    """Certify one simplex using the inherited per-region interval state."""

    region_name, simplex_index, simplex = task
    polynomial_coefficients, vertices, degree = _SIMPLEX_CONTEXT
    simplex_vertices = [vertices[name] for name in simplex["vertices"]]
    determinant = _simplex_determinant(simplex_vertices)
    if determinant.lower <= 0 <= determinant.upper:
        raise AssertionError(
            f"region {region_name} simplex is not certified nondegenerate: "
            f"{simplex['vertices']}")
    orientation_sign = 1 if determinant.lower > 0 else -1
    transformed = _compose(
        polynomial_coefficients, simplex_vertices, degree)
    coefficients = _bernstein_coefficients(transformed, degree)
    zero_indices = {
        tuple(index) for index in simplex["structural_zero_indices"]
    }
    for index in zero_indices:
        enclosure = coefficients[index]
        if not enclosure.lower <= 0 <= enclosure.upper:
            raise AssertionError(
                f"region {region_name} structural-zero enclosure "
                f"{index} does not contain zero")
    positive = {
        index: value for index, value in coefficients.items()
        if index not in zero_indices
    }
    minimum_index, minimum = min(
        positive.items(), key=lambda item: item[1].lower)
    if minimum.lower <= 0:
        raise AssertionError(
            f"region {region_name} coefficient {minimum_index} "
            f"is not certified positive: {minimum}")
    return {
        "vertices": simplex["vertices"],
        "degree": degree,
        "coefficient_count": len(coefficients),
        "structural_zero_count": len(zero_indices),
        "affine_determinant": _interval_record(determinant),
        "orientation_sign": orientation_sign,
        "minimum_positive_index": list(minimum_index),
        "minimum_positive_coefficient": _interval_record(minimum),
    }, minimum


def certify_level(alpha_text, structure):
    brackets = exact_binomial_factor_brackets(
        6, alpha_text, FACTOR_BITS)
    p = [Interval(lower, upper) for lower, upper in brackets]

    a = 1 - p[5]
    b = p[5] - p[4]
    c = p[4] - p[3]
    d = p[3] - p[2]
    e = p[2] - p[1]
    f = p[1] - p[0]
    g = p[0]
    weights = (a, b, c, d, e, f, g)
    for name, weight in zip("abcdefg", weights):
        if weight.lower <= 0:
            raise AssertionError(f"weight {name} is not positive")

    values = {name: value for name, value in zip(
        "bcdefg", (b, c, d, e, f, g))}
    vertices = _vertices(structure, values)

    region_records = {}
    global_minimum = None
    for region_name in ("A", "B", "C", "D", "E", "F"):
        print(f"alpha={alpha_text}: certifying region {region_name}",
              flush=True)
        region = structure["regions"][region_name]
        degree = region["degree"]
        polynomial_coefficients = [
            {
                "powers": item["powers"],
                "value": _evaluate_formula(item["expression"], values),
            }
            for item in region["polynomial_coefficients"]
        ]
        global _SIMPLEX_CONTEXT
        _SIMPLEX_CONTEXT = (polynomial_coefficients, vertices, degree)
        tasks = [(region_name, index, simplex)
                 for index, simplex in enumerate(region["simplices"])]
        workers = min(len(tasks), os.cpu_count() or 1)
        if workers == 1:
            results = [_certify_simplex(task) for task in tasks]
        else:
            with mp.get_context("fork").Pool(workers) as pool:
                results = pool.map(_certify_simplex, tasks)
        simplex_records = [record for record, _ in results]
        for _, minimum in results:
            if global_minimum is None or minimum.lower < global_minimum.lower:
                global_minimum = minimum
        region_records[region_name] = {
            "alpha_identity": region["alpha_identity"],
            "extracted_nonnegative_factors":
                region["extracted_nonnegative_factors"],
            "vertex_region_certificate": _certify_region_vertices(
                region_name, region, vertices,
                structure["vertex_boundary_identities"], weights),
            "simplices": simplex_records,
        }

    return {
        "alpha": alpha_text,
        "nominal_confidence": str(1 - Fraction(alpha_text)),
        "factor_bits": FACTOR_BITS,
        "interval_bits": INTERVAL_BITS,
        "factor_brackets": [_interval_record(value) for value in p],
        "weight_brackets": {
            name: _interval_record(value)
            for name, value in zip("abcdefg", weights)
        },
        "face_normal_rank_certificate":
            _certify_face_normal_ranks(structure, weights),
        "polynomial_regions": region_records,
        "triangulation_chain_certificate": _certify_global_chain(
            structure, region_records, vertices),
        "minimum_positive_bernstein_coefficient":
            _interval_record(global_minimum),
        "conclusion": (
            "For n=6 at this alpha, the binomial Stringer bound "
            "pointwise dominates the one-sided Gaffke bound."
        ),
    }


def build_certificate():
    structure, structure_sha256 = _load_structure()
    if structure.get("face_order_verification") != (
            "exact_generic_differential_ideal_membership"):
        raise ValueError(
            "n=6 structure lacks exact face-order verification")
    return {
        "schema_version": 1,
        "claim": (
            "At n=6 and nominal confidence 90%, 95%, or 99%, the "
            "binomial-factor Stringer bound pointwise dominates the "
            "one-sided Gaffke bound and is therefore distribution-free "
            "conservative under independent sampling."
        ),
        "arithmetic": (
            "Integer-directed dyadic interval arithmetic with exact outward "
            f"rounding at {INTERVAL_BITS} fractional bits; Clopper--Pearson "
            "factor brackets have integer-checked dyadic endpoint signs."
        ),
        "structure_file": str(STRUCTURE_PATH.relative_to(HERE.parents[2])),
        "structure_sha256": structure_sha256,
        "levels": [certify_level(alpha, structure) for alpha in ALPHAS],
    }


def check_level_against(alpha, certificate_path):
    """Regenerate one level and compare it exactly with the bound artifact.

    This split mode preserves the same arithmetic and level record as the
    monolithic generator while allowing the three expensive levels to run in
    separate CI jobs.
    """

    structure, structure_sha256 = _load_structure()
    if structure.get("face_order_verification") != (
            "exact_generic_differential_ideal_membership"):
        raise ValueError("n=6 structure lacks exact face proof")
    certificate = json.loads(certificate_path.read_text())
    if certificate.get("structure_sha256") != structure_sha256:
        raise AssertionError(
            "n=6 certificate is not bound to the committed structure")
    matches = [level for level in certificate.get("levels", [])
               if level.get("alpha") == alpha]
    if len(matches) != 1:
        raise AssertionError(
            f"expected one committed n=6 level for alpha={alpha}")
    observed = certify_level(alpha, structure)
    if observed != matches[0]:
        raise AssertionError(
            f"regenerated n=6 level differs at alpha={alpha}")
    print(f"n=6 level regeneration at alpha={alpha}: PASS", flush=True)


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path,
                        help="write the machine-readable certificate")
    parser.add_argument(
        "--check-alpha", choices=ALPHAS,
        help=("regenerate one level and compare it with the committed "
              "certificate"),
    )
    parser.add_argument(
        "--against", type=Path, default=DEFAULT_CERTIFICATE_PATH,
        help="certificate artifact used by --check-alpha",
    )
    parser.add_argument(
        "--allow-unverified-structure", action="store_true",
        help="development only: accept a structure made with --skip-face-proof",
    )
    args = parser.parse_args(argv)
    if args.check_alpha:
        if args.out:
            parser.error("--check-alpha conflicts with --out")
        if args.allow_unverified_structure:
            parser.error(
                "--allow-unverified-structure conflicts with --check-alpha")
        check_level_against(args.check_alpha, args.against)
        return 0
    if args.against != DEFAULT_CERTIFICATE_PATH:
        parser.error("--against requires --check-alpha")
    structure, _ = _load_structure()
    if (structure.get("face_order_verification") !=
            "exact_generic_differential_ideal_membership"):
        if not args.allow_unverified_structure:
            raise ValueError("n=6 structure lacks exact face proof")
        # Development path; build_certificate intentionally rejects this.
        original = structure["face_order_verification"]
        structure["face_order_verification"] = (
            "exact_generic_differential_ideal_membership")
        certificate = {
            "schema_version": 0,
            "development_only": True,
            "original_face_order_verification": original,
            "levels": [certify_level(alpha, structure) for alpha in ALPHAS],
        }
    else:
        certificate = build_certificate()
    rendered = json.dumps(certificate, indent=2, sort_keys=True) + "\n"
    if args.out:
        args.out.write_text(rendered)
    for level in certificate["levels"]:
        minimum = level["minimum_positive_bernstein_coefficient"]
        print(
            f"alpha={level['alpha']}: certified; "
            f"minimum positive Bernstein lower bound="
            f"{minimum['lower']['decimal']}"
        )
    print("n6_gaffke_certificate: all exact sign checks passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
