"""Rigorous ball certificate for conventional-level coverage at ``n=7``.

Clopper--Pearson roots are first enclosed by dyadic rationals whose endpoint
signs are checked with integer arithmetic.  Every subsequent weight, vertex,
determinant, residual, and Bernstein operation uses rigorous Arb real-ball
arithmetic through python-flint.  Generic structural zeros are supplied by
the SHA-bound exact Singular structure artifact.
"""

from __future__ import annotations

import argparse
import gzip
import hashlib
import itertools
import json
import math
import multiprocessing as mp
import os
from collections import defaultdict
from fractions import Fraction
from pathlib import Path

import flint
from flint import arb, ctx, fmpq

from n7_gaffke_structure_data import (
    DIMENSION,
    REFLECTED_REGIONS,
    REGION_NAMES,
    structural_zero_indices,
)
from stringer import exact_binomial_factor_brackets


ALPHAS = ("0.01", "0.05", "0.10")
FACTOR_BITS = 512
BALL_BITS = 768
N = 7
HERE = Path(__file__).resolve().parent
CERTIFICATE_DIR = HERE.parent / "certificates"
STRUCTURE_PATH = CERTIFICATE_DIR / "n7-gaffke-bernstein-structure.json.gz"
DEFAULT_CERTIFICATE_PATH = CERTIFICATE_DIR / "n7-gaffke-certificate.json"
COORDINATE_NAMES = ("x", "y", "z", "w", "u", "v")
WEIGHT_NAMES = ("b", "c", "d", "e", "f", "g", "h")
ZERO = (0,) * DIMENSION


def _fmpq(value):
    value = Fraction(value)
    return fmpq(value.numerator, value.denominator)


def _ball_from_interval(lower, upper):
    center = (lower+upper)/2
    radius = (upper-lower)/2
    return arb(_fmpq(center), _fmpq(radius))


def _fmpq_record(value):
    return {
        "numerator": str(value.p),
        "denominator": str(value.q),
        "decimal": arb(value).str(12, radius=False),
    }


def _ball_record(value):
    return {
        "lower": _fmpq_record(value.lower().fmpq()),
        "upper": _fmpq_record(value.upper().fmpq()),
    }


def _read_structure():
    raw = STRUCTURE_PATH.read_bytes()
    with gzip.open(STRUCTURE_PATH, "rt") as handle:
        structure = json.load(handle)
    if structure.get("schema_version") != 2:
        raise ValueError("unexpected n=7 structure schema")
    if structure.get("face_order_verification") != (
            "exact_generic_I_adic_factor_order_or_Singular_quotient_Horner_"
            "ideal_power_membership"):
        raise ValueError("n=7 structure lacks exact generic face proofs")
    face_records = structure.get("generic_face_order_certificates", [])
    if len(face_records) != 26:
        raise ValueError("n=7 structure lacks 26 generic face proofs")
    factor_count = sum(
        record.get("verification", "").startswith("exact_I_adic_")
        for record in face_records)
    singular_count = sum(
        "Singular" in record.get("verification", "")
        for record in face_records)
    if (factor_count, singular_count) != (22, 4):
        raise ValueError("unexpected n=7 generic face-proof split")
    return structure, hashlib.sha256(raw).hexdigest()


def _evaluate_formula(text, values):
    # The expressions are generated by Singular/SymPy, stored in the
    # SHA-bound structure artifact, and contain only integer arithmetic and
    # the seven whitelisted variable names.
    return eval(text, {"__builtins__": {}}, values)


def _vertices(structure, values):
    output = {}
    for name, formulas in structure["vertex_formulas"].items():
        point = []
        for formula in formulas:
            value = _evaluate_formula(formula, values)
            point.append(value if isinstance(value, arb) else arb(value))
        output[name] = tuple(point)
    return output


def _add(left, right):
    output = dict(left)
    for index, value in right.items():
        result = output.get(index, arb(0)) + value
        if result == 0:
            output.pop(index, None)
        else:
            output[index] = result
    return output


def _multiply_linear(polynomial, constant, vector):
    output = {}
    for powers, coefficient in polynomial.items():
        if constant != 0:
            output[powers] = (
                output.get(powers, arb(0)) + coefficient*constant)
        for axis, value in enumerate(vector):
            if value != 0:
                child = list(powers)
                child[axis] += 1
                child = tuple(child)
                output[child] = (
                    output.get(child, arb(0)) + coefficient*value)
    return {index: value for index, value in output.items() if value != 0}


def _compose_horner(polynomial, affine, axis=0):
    if not polynomial:
        return {}
    if axis == DIMENSION:
        value = sum(polynomial.values(), arb(0))
        return {ZERO: value} if value != 0 else {}
    groups = defaultdict(dict)
    for powers, coefficient in polynomial.items():
        exponent = powers[axis]
        child = list(powers)
        child[axis] = 0
        groups[exponent][tuple(child)] = coefficient
    composed = {
        exponent: _compose_horner(group, affine, axis+1)
        for exponent, group in groups.items()
    }
    output = {}
    constant, vector = affine[axis]
    for exponent in range(max(groups), -1, -1):
        if output:
            output = _multiply_linear(output, constant, vector)
        if exponent in composed:
            output = _add(output, composed[exponent])
    return output


def _bernstein_coefficients(power_polynomial, degree):
    data = {}
    factorial = math.factorial
    for powers, coefficient in power_polynomial.items():
        multinomial = factorial(degree)//factorial(degree-sum(powers))
        for exponent in powers:
            multinomial //= factorial(exponent)
        data[powers] = coefficient/multinomial
    for axis in range(DIMENSION):
        groups = defaultdict(dict)
        for powers, coefficient in data.items():
            key = powers[:axis] + powers[axis+1:]
            groups[key][powers[axis]] = coefficient
        transformed = {}
        for key, values in groups.items():
            cap = degree-sum(key)
            vector = [values.get(i, arb(0)) for i in range(cap+1)]
            for upper in range(cap+1):
                value = sum(
                    (math.comb(upper, lower)*vector[lower]
                     for lower in range(upper+1)),
                    arb(0),
                )
                powers = list(key)
                powers.insert(axis, upper)
                transformed[tuple(powers)] = value
        data = transformed
    return data


def _permutation_sign(permutation):
    inversions = sum(
        permutation[i] > permutation[j]
        for i in range(len(permutation))
        for j in range(i+1, len(permutation))
    )
    return -1 if inversions % 2 else 1


def _matrix_determinant(matrix):
    determinant = arb(0)
    for permutation in itertools.permutations(range(len(matrix))):
        term = arb(_permutation_sign(permutation))
        for row, column in enumerate(permutation):
            term *= matrix[row][column]
        determinant += term
    return determinant


def _simplex_determinant(points):
    return _matrix_determinant([
        [points[column+1][row]-points[0][row]
         for column in range(DIMENSION)]
        for row in range(DIMENSION)
    ])


def _reflected_point(point):
    return tuple(1-point[DIMENSION-1-index]
                 for index in range(DIMENSION))


_SIMPLEX_CONTEXT = None


def _certify_simplex(task):
    region, simplex_index, simplex = task
    (polynomial, vertices, degree, reflected,
     conditions) = _SIMPLEX_CONTEXT
    actual_points = [vertices[name] for name in simplex["vertices"]]
    determinant = _simplex_determinant(actual_points)
    if not (determinant > 0 or determinant < 0):
        raise AssertionError(
            f"region {region} simplex {simplex_index} is not nondegenerate")
    orientation = 1 if determinant > 0 else -1
    polynomial_points = (
        [_reflected_point(point) for point in actual_points]
        if reflected else actual_points
    )
    origin = polynomial_points[0]
    affine = [
        (origin[coordinate], tuple(
            polynomial_points[index+1][coordinate]-origin[coordinate]
            for index in range(DIMENSION)))
        for coordinate in range(DIMENSION)
    ]
    transformed = _compose_horner(polynomial, affine)
    if reflected:
        transformed = {index: -value
                       for index, value in transformed.items()}
    coefficients = _bernstein_coefficients(transformed, degree)
    zero_indices = set(structural_zero_indices(degree, conditions))
    for index in zero_indices:
        powers = index[:-1]
        value = coefficients.get(powers, arb(0))
        if 0 not in value:
            raise AssertionError(
                f"region {region} structural zero {index} excludes zero")
    minimum = None
    minimum_index = None
    positive_count = 0
    expected_count = math.comb(degree+DIMENSION, DIMENSION)
    for powers in _power_indices(degree):
        index = powers + (degree-sum(powers),)
        if index in zero_indices:
            continue
        value = coefficients.get(powers, arb(0))
        if not value > 0:
            raise AssertionError(
                f"region {region} coefficient {index} is not positive: "
                f"{value}")
        lower = value.lower().fmpq()
        if minimum is None or lower < minimum:
            minimum = lower
            minimum_index = index
        positive_count += 1
    if positive_count+len(zero_indices) != expected_count:
        raise AssertionError("wrong n=7 Bernstein coefficient count")
    return ({
        "vertices": simplex["vertices"],
        "degree": degree,
        "coefficient_count": expected_count,
        "structural_zero_count": len(zero_indices),
        "affine_determinant": _ball_record(determinant),
        "orientation_sign": orientation,
        "minimum_positive_index": list(minimum_index),
        "minimum_positive_lower_bound": _fmpq_record(minimum),
    }, minimum)


def _power_indices(degree, dimension=DIMENSION):
    if dimension == 1:
        for value in range(degree+1):
            yield (value,)
        return
    for value in range(degree+1):
        for suffix in _power_indices(degree-value, dimension-1):
            yield (value,) + suffix


DOMAIN_BOUNDARY_LABELS = (
    "x=0", "x=y", "y=z", "z=w", "w=u", "u=v", "v=1",
)


def _vertex_forms(point, weights):
    x, y, z, w, u, v = point
    b, c, d, e, f, g = weights[1:7]
    h = weights[7]
    s = b*x+c*y+d*z+e*w+f*u+g*v+h
    return {
        "x=0": x, "x=y": y-x, "y=z": z-y,
        "z=w": w-z, "w=u": u-w, "u=v": v-u,
        "v=1": 1-v,
        "s=x": s-x, "s=y": s-y, "s=z": s-z,
        "s=w": s-w, "s=u": s-u, "s=v": s-v,
    }


def _certify_region_vertices(region, record, vertices, identities, weights):
    forms_by_region = {
        "A": (("s=v", 1),),
        "B": (("s=u", 1), ("s=v", -1)),
        "C": (("s=w", 1), ("s=u", -1)),
        "D": (("s=z", 1), ("s=w", -1)),
        "E": (("s=y", 1), ("s=z", -1)),
        "F": (("s=x", 1), ("s=y", -1)),
        "G": (("s=x", -1),),
    }[region]
    names = sorted({name for simplex in record["simplices"]
                    for name in simplex["vertices"]})
    minimum = None
    checked = 0
    zeros = 0
    for name in names:
        forms = _vertex_forms(vertices[name], weights)
        checks = tuple((label, 1) for label in DOMAIN_BOUNDARY_LABELS)
        checks += forms_by_region
        for label, sign in checks:
            value = forms[label] if sign > 0 else -forms[label]
            if label in identities[name]:
                if 0 not in value:
                    raise AssertionError((region, name, label, value))
                zeros += 1
            else:
                if not value > 0:
                    raise AssertionError((region, name, label, value))
                lower = value.lower().fmpq()
                if minimum is None or lower < minimum:
                    minimum = lower
            checked += 1
    return {
        "vertex_count": len(names),
        "ordered_domain_and_region_inequalities_checked": checked,
        "exact_boundary_equalities_used": zeros,
        "minimum_strict_vertex_slack_lower_bound": _fmpq_record(minimum),
    }


def _normal_rows(weights):
    b, c, d, e, f, g = weights[1:7]
    return {
        "x=0": (1, 0, 0, 0, 0, 0),
        "x=y": (-1, 1, 0, 0, 0, 0),
        "y=z": (0, -1, 1, 0, 0, 0),
        "z=w": (0, 0, -1, 1, 0, 0),
        "w=u": (0, 0, 0, -1, 1, 0),
        "u=v": (0, 0, 0, 0, -1, 1),
        "v=1": (0, 0, 0, 0, 0, -1),
        "s=x": (b-1, c, d, e, f, g),
        "s=y": (b, c-1, d, e, f, g),
        "s=z": (b, c, d-1, e, f, g),
        "s=w": (b, c, d, e-1, f, g),
        "s=u": (b, c, d, e, f-1, g),
        "s=v": (b, c, d, e, f, g-1),
    }


def _certify_face_normal_ranks(structure, weights):
    """Certify geometric faces, proof-source ideals, and proof pivots.

    Reflected regions use a source residual at the reversed full weight
    vector.  Rank must therefore be checked not only for the face equations
    in the displayed region, but also for the particular generator basis and
    proof-source pivot used to justify its restriction or inverse chart under
    the corresponding original or reversed box.
    """

    proof_instances = [
        (region_name, proof)
        for region_name, region in structure["regions"].items()
        for simplex in region["simplices"]
        for proof in simplex["face_order_proofs"]
    ]
    proofs = [proof for _, proof in proof_instances]
    generator_sets = {
        tuple(proof["independent_ideal_generators"])
        for proof in proofs
    }
    generic_proof_keys = {
        (
            proof["proof_source_region"],
            tuple(proof["proof_source_ideal_generators"]),
            proof["vanishing_order"],
        )
        for proof in proofs
    }
    source_generator_sets = {
        (
            "reversed" if region_name in REFLECTED_REGIONS else "original",
            proof["proof_source_region"],
            tuple(proof["proof_source_ideal_generators"]),
            tuple(proof["proof_source_inverse_pivot_columns"]),
        )
        for region_name, proof in proof_instances
    }
    rows_by_orientation = {
        "original": _normal_rows(weights),
        "reversed": _normal_rows(tuple(reversed(weights))),
    }

    def certify_sets(tagged_sets, fixed_inverse_pivot=False):
        records = []
        minimum = None
        for tagged in sorted(
                tagged_sets,
                key=lambda value: (len(value[2]), value)):
            orientation, source_region, labels = tagged[:3]
            rows = rows_by_orientation[orientation]
            candidates = []
            if fixed_inverse_pivot:
                stored_columns = tagged[3]
                if len(stored_columns) != len(labels):
                    raise AssertionError(
                        f"wrong proof inverse pivot: {labels}, "
                        f"{stored_columns}")
                column_sets = [tuple(
                    COORDINATE_NAMES.index(name)
                    for name in stored_columns
                )]
            else:
                stored_columns = None
                column_sets = itertools.combinations(
                    range(DIMENSION), len(labels))
            for columns in column_sets:
                determinant = _matrix_determinant([
                    [rows[label][column] for column in columns]
                    for label in labels
                ])
                if determinant > 0:
                    margin = determinant.lower().fmpq()
                elif determinant < 0:
                    margin = (-determinant).lower().fmpq()
                else:
                    continue
                candidates.append((margin, columns, determinant))
            if not candidates:
                raise AssertionError(
                    f"face normals lose rank: {orientation}, {labels}")
            margin, columns, determinant = max(
                candidates, key=lambda item: item[0])
            if minimum is None or margin < minimum:
                minimum = margin
            record = {
                "weight_orientation": orientation,
                "independent_ideal_generators": list(labels),
                "minor_coordinate_columns": [
                    COORDINATE_NAMES[i] for i in columns],
                "normal_minor_determinant": _ball_record(determinant),
            }
            if source_region is not None:
                record["proof_source_region"] = source_region
            if stored_columns is not None:
                record["exact_proof_inverse_pivot_columns"] = list(
                    stored_columns)
            records.append(record)
        return records, minimum

    actual_records, actual_minimum = certify_sets({
        ("original", None, labels) for labels in generator_sets
    })
    source_records, source_minimum = certify_sets(
        source_generator_sets, fixed_inverse_pivot=True)
    minimum = min(actual_minimum, source_minimum)
    return {
        "generator_sets_certified": len(actual_records),
        "proof_source_generator_sets_certified": len(source_records),
        "simplex_face_order_conditions_linked": len(proofs),
        "distinct_generic_ideal_power_proofs_linked":
            len(generic_proof_keys),
        "minimum_absolute_normal_minor_lower_bound": _fmpq_record(minimum),
        "sets": actual_records,
        "proof_source_sets": source_records,
        "conclusion": (
            "Every geometric face-generator set and every source-ideal "
            "generator set used by the exact generic ideal-power proofs "
            "retains full normal rank throughout its original or reflected "
            "certified weight box; in particular, every proof-source pivot "
            "used to justify a restriction or inverse chart remains "
            "nonsingular."
        ),
    }


def _permutation_sign_for_names(sequence, canonical):
    positions = [canonical.index(value) for value in sequence]
    return _permutation_sign(positions)


def _certify_global_chain(structure, region_records, vertices):
    distinct = 0
    for left, right in itertools.combinations(sorted(vertices), 2):
        if not any((vertices[left][coordinate]-vertices[right][coordinate]) > 0
                   or (vertices[left][coordinate]-vertices[right][coordinate]) < 0
                   for coordinate in range(DIMENSION)):
            raise AssertionError(f"vertices not distinct: {left}, {right}")
        distinct += 1
    incidences = {}
    total = arb(0)
    simplex_count = 0
    for region in REGION_NAMES:
        structure_simplices = structure["regions"][region]["simplices"]
        certified = region_records[region]["simplices"]
        for source, record in zip(structure_simplices, certified):
            names = source["vertices"]
            points = [vertices[name] for name in names]
            determinant = _simplex_determinant(points)
            orientation = record["orientation_sign"]
            total += determinant if orientation > 0 else -determinant
            for removed in range(DIMENSION+1):
                raw_face = names[:removed]+names[removed+1:]
                canonical = tuple(sorted(raw_face))
                coefficient = (
                    orientation*((-1)**removed)
                    * _permutation_sign_for_names(raw_face, canonical)
                )
                incidences.setdefault(canonical, []).append(coefficient)
            simplex_count += 1
    internal = 0
    boundary = 0
    boundary_counts = {label: 0 for label in DOMAIN_BOUNDARY_LABELS}
    identities = structure["vertex_boundary_identities"]
    for face, coefficients in incidences.items():
        if len(coefficients) == 2:
            if sum(coefficients) != 0:
                raise AssertionError(("noncancelling facet", face, coefficients))
            internal += 1
        elif len(coefficients) == 1:
            common = set(DOMAIN_BOUNDARY_LABELS)
            for name in face:
                common.intersection_update(identities[name])
            if len(common) != 1:
                raise AssertionError(("bad boundary facet", face, common))
            boundary_counts[next(iter(common))] += 1
            boundary += 1
        else:
            raise AssertionError(("bad facet incidence", face, coefficients))
    if not (total > arb("1/2") and total < arb("3/2") and 1 in total):
        raise AssertionError(f"triangulation degree is not one: {total}")
    return {
        "simplex_count": simplex_count,
        "distinct_vertex_pairs_certified": distinct,
        "internal_facets_paired_with_opposite_orientation": internal,
        "unpaired_outer_boundary_facets": boundary,
        "outer_boundary_facets_by_hyperplane": boundary_counts,
        "normalized_oriented_volume": _ball_record(total),
        "integer_relative_chain_degree": 1,
    }


def _evaluate_source(source, values):
    polynomial = {}
    for item in source["polynomial_coefficients"]:
        value = _evaluate_formula(item["expression"], values)
        polynomial[tuple(item["powers"])] = (
            value if isinstance(value, arb) else arb(value))
    return polynomial


def certify_level(alpha_text, structure):
    ctx.prec = BALL_BITS
    brackets = exact_binomial_factor_brackets(N, alpha_text, FACTOR_BITS)
    p = [_ball_from_interval(lower, upper) for lower, upper in brackets]
    weights = [1-p[N-1]]
    weights.extend(p[N-i]-p[N-i-1] for i in range(1, N))
    weights.append(p[0])
    weights = tuple(weights)
    if not all(weight > 0 for weight in weights):
        raise AssertionError("n=7 increment is not positive")
    values = dict(zip(WEIGHT_NAMES, weights[1:]))
    vertices = _vertices(structure, values)
    region_records = {}
    global_minimum = None
    for region in REGION_NAMES:
        print(f"alpha={alpha_text}: certifying n=7 region {region}", flush=True)
        record = structure["regions"][region]
        source_weights = tuple(reversed(weights)) \
            if region in REFLECTED_REGIONS else weights
        source_values = dict(zip(WEIGHT_NAMES, source_weights[1:]))
        polynomial = _evaluate_source(
            structure["polynomial_sources"][record["source_region"]],
            source_values,
        )
        global _SIMPLEX_CONTEXT
        conditions = [
            [(tuple(subset), maximum)
             for subset, maximum in simplex["face_conditions"]]
            for simplex in record["simplices"]
        ]
        tasks = [
            (region, index, simplex)
            for index, simplex in enumerate(record["simplices"])
        ]
        # Each task receives its own face conditions through the task-local
        # copy of the simplex record to keep the forked context read-only.
        context_conditions = {index: condition
                              for index, condition in enumerate(conditions)}
        _SIMPLEX_CONTEXT = (
            polynomial, vertices, record["degree"],
            region in REFLECTED_REGIONS, context_conditions,
        )
        # Normalize the condition lookup in a tiny wrapper context used by
        # _certify_simplex.
        original_context = _SIMPLEX_CONTEXT
        workers = min(len(tasks), int(os.environ.get("N7_WORKERS", "8")),
                      os.cpu_count() or 1)
        if workers == 1 or "fork" not in mp.get_all_start_methods():
            results = [_certify_simplex_with_conditions(task)
                       for task in tasks]
        else:
            with mp.get_context("fork").Pool(workers) as pool:
                results = pool.map(_certify_simplex_with_conditions, tasks)
        _SIMPLEX_CONTEXT = original_context
        simplices = [item for item, _ in results]
        region_minimum = min(minimum for _, minimum in results)
        if global_minimum is None or region_minimum < global_minimum:
            global_minimum = region_minimum
        region_records[region] = {
            "alpha_identity": record["alpha_identity"],
            "extracted_nonnegative_factors":
                record["extracted_nonnegative_factors"],
            "source_region": record["source_region"],
            "reflection_applied": record["reflection_applied"],
            "vertex_region_certificate": _certify_region_vertices(
                region, record, vertices,
                structure["vertex_boundary_identities"], weights),
            "minimum_positive_lower_bound": _fmpq_record(region_minimum),
            "simplices": simplices,
        }
    return {
        "alpha": alpha_text,
        "nominal_confidence": str(1-Fraction(alpha_text)),
        "factor_bits": FACTOR_BITS,
        "arb_precision_bits": BALL_BITS,
        "factor_brackets": [_ball_record(value) for value in p],
        "weight_brackets": {
            name: _ball_record(value)
            for name, value in zip("abcdefgh", weights)
        },
        "face_normal_rank_certificate":
            _certify_face_normal_ranks(structure, weights),
        "polynomial_regions": region_records,
        "triangulation_chain_certificate": _certify_global_chain(
            structure, region_records, vertices),
        "minimum_positive_bernstein_lower_bound":
            _fmpq_record(global_minimum),
        "conclusion": (
            "For n=7 at this alpha, the binomial Stringer bound "
            "pointwise dominates the one-sided Gaffke bound."
        ),
    }


def _certify_simplex_with_conditions(task):
    global _SIMPLEX_CONTEXT
    polynomial, vertices, degree, reflected, conditions = _SIMPLEX_CONTEXT
    region, simplex_index, simplex = task
    _SIMPLEX_CONTEXT = (
        polynomial, vertices, degree, reflected, conditions[simplex_index])
    try:
        return _certify_simplex(task)
    finally:
        _SIMPLEX_CONTEXT = (
            polynomial, vertices, degree, reflected, conditions)


def build_certificate():
    structure, digest = _read_structure()
    return {
        "schema_version": 1,
        "claim": (
            "At n=7 and nominal confidence 90%, 95%, or 99%, the "
            "binomial-factor Stringer bound pointwise dominates the "
            "one-sided Gaffke bound and is therefore distribution-free "
            "conservative under independent sampling."
        ),
        "arithmetic": (
            "Integer-checked dyadic Clopper--Pearson brackets followed by "
            f"rigorous Arb real-ball arithmetic at {BALL_BITS} bits through "
            f"python-flint {flint.__version__}."
        ),
        "structure_file": str(STRUCTURE_PATH.relative_to(HERE.parents[2])),
        "structure_sha256": digest,
        "levels": [certify_level(alpha, structure) for alpha in ALPHAS],
    }


def check_level_against(alpha, certificate_path):
    structure, digest = _read_structure()
    certificate = json.loads(certificate_path.read_text())
    if certificate.get("structure_sha256") != digest:
        raise AssertionError("n=7 certificate structure digest differs")
    expected = [level for level in certificate.get("levels", [])
                if level.get("alpha") == alpha]
    if len(expected) != 1:
        raise AssertionError(f"expected one n=7 level at alpha={alpha}")
    observed = certify_level(alpha, structure)
    if observed != expected[0]:
        raise AssertionError(f"regenerated n=7 level differs at {alpha}")
    print(f"n=7 level regeneration at alpha={alpha}: PASS")


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path)
    parser.add_argument("--check-alpha", choices=ALPHAS)
    parser.add_argument("--against", type=Path,
                        default=DEFAULT_CERTIFICATE_PATH)
    args = parser.parse_args(argv)
    if args.check_alpha:
        if args.out:
            parser.error("--check-alpha conflicts with --out")
        check_level_against(args.check_alpha, args.against)
        return 0
    if args.against != DEFAULT_CERTIFICATE_PATH:
        parser.error("--against requires --check-alpha")
    certificate = build_certificate()
    rendered = json.dumps(certificate, indent=2, sort_keys=True)+"\n"
    if args.out:
        args.out.write_text(rendered)
    for level in certificate["levels"]:
        print(
            f"alpha={level['alpha']}: n=7 certified; minimum lower bound="
            f"{level['minimum_positive_bernstein_lower_bound']['decimal']}"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
